"""4.2.0 Added type_ attribut in Sale_product_group

Revision ID: 18b6a30326e2
Revises: 182bf34f7989
Create Date: 2018-10-10 19:24:06.883866

"""

# revision identifiers, used by Alembic.
revision = '18b6a30326e2'
down_revision = '182bf34f7989'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def update_database_structure():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_product_group', sa.Column('type_', sa.String(length=30), nullable=False))

def migrate_datas():
    from autonomie_base.models.base import DBSESSION
    session = DBSESSION()
    from alembic.context import get_bind
    connection = get_bind()
    op.execute("UPDATE sale_product_group SET type_='base'")
    from zope.sqlalchemy import mark_changed
    mark_changed(session)

def upgrade():
    update_database_structure()
    migrate_datas()


def downgrade():
    op.drop_column('sale_product_group', 'type_')
