"""4.2.0 Added registration attribute to customer model

Revision ID: 118382521263
Revises: 3885e8260693
Create Date: 2018-11-06 11:41:27.050354

"""

# revision identifiers, used by Alembic.
revision = '118382521263'
down_revision = '3885e8260693'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def update_database_structure():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('registration', sa.String(length=50), nullable=True))
    ### end Alembic commands ###

def migrate_datas():
    from autonomie_base.models.base import DBSESSION
    session = DBSESSION()
    from alembic.context import get_bind
    conn = get_bind()

def upgrade():
    update_database_structure()
    migrate_datas()


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'registration')
    ### end Alembic commands ###
